CREATE TABLE [dbo].[ProjectCloseouts] (
    [ProjectId]                    INT            NOT NULL,
    [CloseoutReasonId]             INT            NOT NULL,
    [CommercialMilestonesComplete] BIT            NOT NULL,
    [DeliverablesComplete]         BIT            NOT NULL,
    [CustomerDataManagement]       VARCHAR (MAX)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SalesLearnings]               VARCHAR (MAX)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OpsLearnings]                 VARCHAR (MAX)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [LearningActions]              VARCHAR (MAX)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FollowUpActions]              VARCHAR (MAX)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CommercialScoreId]            INT            NOT NULL,
    [OperationalScoreId]           INT            NOT NULL,
    [BusinessDevelopmentScoreId]   INT            NOT NULL,
    [ReputationalScoreId]          INT            NOT NULL,
    [ResourceProfileScoreId]       INT            NOT NULL,
    [ProjectScore]                 INT            NOT NULL,
    [CreatedById]                  NVARCHAR (450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DateCreated]                  DATETIME       NOT NULL,
    [CustomerFeedback]             BIT            CONSTRAINT [DF_ProjectCloseouts_CustomerFeedback] DEFAULT ((0)) NOT NULL,
    [DataPurged]                   BIT            NOT NULL,
    [CaseStudy]                    BIT            NOT NULL,
    [FeedBack]                     VARCHAR (MAX)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT [PK_ProjectCloseouts] PRIMARY KEY CLUSTERED ([ProjectId] ASC),
    CONSTRAINT [FK_ProjectCloseouts_BusinessDevelopmentScores] FOREIGN KEY ([BusinessDevelopmentScoreId]) REFERENCES [dbo].[BusinessDevelopmentScores] ([Id]),
    CONSTRAINT [FK_ProjectCloseouts_CloseoutReasons] FOREIGN KEY ([CloseoutReasonId]) REFERENCES [dbo].[CloseoutReasons] ([Id]),
    CONSTRAINT [FK_ProjectCloseouts_CommercialScores] FOREIGN KEY ([CommercialScoreId]) REFERENCES [dbo].[CommercialScores] ([Id]),
    CONSTRAINT [FK_ProjectCloseouts_OperationalScores] FOREIGN KEY ([OperationalScoreId]) REFERENCES [dbo].[OperationalScores] ([Id]),
    CONSTRAINT [FK_ProjectCloseouts_ProjectCloseouts] FOREIGN KEY ([ProjectId]) REFERENCES [dbo].[ProjectCloseouts] ([ProjectId]),
    CONSTRAINT [FK_ProjectCloseouts_Projects] FOREIGN KEY ([ProjectId]) REFERENCES [dbo].[Projects] ([Id]),
    CONSTRAINT [FK_ProjectCloseouts_ReputationalScores] FOREIGN KEY ([ReputationalScoreId]) REFERENCES [dbo].[ReputationalScores] ([Id])
);

